### ISSUE TITLE
Implementation is not same as Equation 3

### ISSUE THREAD

**Issue by quqixun** [dhruvramani/C2AE-Multilabel-Classification#11]
This [line](https://github.com/dhruvramani/C2AE-Multilabel-Classification/blob/master/model/src/network.py#L92) is not quit same as the equation (3) in paper.

Should it be ```1 / (y1 * y0)```at the beginning?

**Comment by Zhen-Zohn-WANG** [comment]
I have the same question and the rest of the implementation for Equation 3 doesn't seem very right.

**Comment by mtxing69** [comment]
same doubt

**Comment by mtxing69** [comment]
The positive-negetive pair is not pairwise calculated, neither. It uses the sum of ones to minus the sum of zeros instead. Maybe it`s a kind of approximation?

**Comment by oslo71** [comment]
I have the same question. BTW, where are the p and q of the equation(3) in the code?
